import { Inter } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/Sidebar';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} flex items-start justify-between`}>
        <Sidebar />
        <main
          className='grid w-full h-full pl-[300px]'
          style={{ width: 'calc(100%-300px)' }}
        >
          <Header />
          <div className='p-8'>{children}</div>
        </main>
      </body>
    </html>
  );
}
